// Auto-generated by scripts/generate-kreis-slugs.ts — do not edit manually
export const AGS_TO_KREIS_SLUG: Record<string, { slug: string; bl: string }> = {
  "10041": {
    "slug": "regionalverband-saarbruecken",
    "bl": "10"
  },
  "10042": {
    "slug": "merzig-wadern",
    "bl": "10"
  },
  "10043": {
    "slug": "neunkirchen",
    "bl": "10"
  },
  "10044": {
    "slug": "saarlouis",
    "bl": "10"
  },
  "10045": {
    "slug": "saarpfalz-kreis",
    "bl": "10"
  },
  "10046": {
    "slug": "st-wendel",
    "bl": "10"
  },
  "11000": {
    "slug": "berlin-stadt",
    "bl": "11"
  },
  "12051": {
    "slug": "brandenburg-an-der-havel-stadt",
    "bl": "12"
  },
  "12052": {
    "slug": "cottbus-stadt",
    "bl": "12"
  },
  "12053": {
    "slug": "frankfurt-oder-stadt",
    "bl": "12"
  },
  "12054": {
    "slug": "potsdam-stadt",
    "bl": "12"
  },
  "12060": {
    "slug": "barnim",
    "bl": "12"
  },
  "12061": {
    "slug": "dahme-spreewald",
    "bl": "12"
  },
  "12062": {
    "slug": "elbe-elster",
    "bl": "12"
  },
  "12063": {
    "slug": "havelland",
    "bl": "12"
  },
  "12064": {
    "slug": "maerkisch-oderland",
    "bl": "12"
  },
  "12065": {
    "slug": "oberhavel",
    "bl": "12"
  },
  "12066": {
    "slug": "oberspreewald-lausitz",
    "bl": "12"
  },
  "12067": {
    "slug": "oder-spree",
    "bl": "12"
  },
  "12068": {
    "slug": "ostprignitz-ruppin",
    "bl": "12"
  },
  "12069": {
    "slug": "potsdam-mittelmark",
    "bl": "12"
  },
  "12070": {
    "slug": "prignitz",
    "bl": "12"
  },
  "12071": {
    "slug": "spree-neisse",
    "bl": "12"
  },
  "12072": {
    "slug": "teltow-flaeming",
    "bl": "12"
  },
  "12073": {
    "slug": "uckermark",
    "bl": "12"
  },
  "13003": {
    "slug": "rostock-stadt",
    "bl": "13"
  },
  "13004": {
    "slug": "schwerin-stadt",
    "bl": "13"
  },
  "13071": {
    "slug": "mecklenburgische-seenplatte",
    "bl": "13"
  },
  "13072": {
    "slug": "rostock",
    "bl": "13"
  },
  "13073": {
    "slug": "vorpommern-ruegen",
    "bl": "13"
  },
  "13074": {
    "slug": "nordwestmecklenburg",
    "bl": "13"
  },
  "13075": {
    "slug": "vorpommern-greifswald",
    "bl": "13"
  },
  "13076": {
    "slug": "ludwigslust-parchim",
    "bl": "13"
  },
  "14511": {
    "slug": "chemnitz-stadt",
    "bl": "14"
  },
  "14521": {
    "slug": "erzgebirgskreis",
    "bl": "14"
  },
  "14522": {
    "slug": "mittelsachsen",
    "bl": "14"
  },
  "14523": {
    "slug": "vogtlandkreis",
    "bl": "14"
  },
  "14524": {
    "slug": "zwickau",
    "bl": "14"
  },
  "14612": {
    "slug": "dresden-stadt",
    "bl": "14"
  },
  "14625": {
    "slug": "bautzen",
    "bl": "14"
  },
  "14626": {
    "slug": "goerlitz",
    "bl": "14"
  },
  "14627": {
    "slug": "meissen",
    "bl": "14"
  },
  "14628": {
    "slug": "saechsische-schweiz-osterzgebirge",
    "bl": "14"
  },
  "14713": {
    "slug": "leipzig-stadt",
    "bl": "14"
  },
  "14729": {
    "slug": "leipzig",
    "bl": "14"
  },
  "14730": {
    "slug": "nordsachsen",
    "bl": "14"
  },
  "15001": {
    "slug": "dessau-rosslau-stadt",
    "bl": "15"
  },
  "15002": {
    "slug": "halle-saale-stadt",
    "bl": "15"
  },
  "15003": {
    "slug": "magdeburg-stadt",
    "bl": "15"
  },
  "15081": {
    "slug": "altmarkkreis-salzwedel",
    "bl": "15"
  },
  "15082": {
    "slug": "anhalt-bitterfeld",
    "bl": "15"
  },
  "15083": {
    "slug": "boerde",
    "bl": "15"
  },
  "15084": {
    "slug": "burgenlandkreis",
    "bl": "15"
  },
  "15085": {
    "slug": "harz",
    "bl": "15"
  },
  "15086": {
    "slug": "jerichower-land",
    "bl": "15"
  },
  "15087": {
    "slug": "mansfeld-suedharz",
    "bl": "15"
  },
  "15088": {
    "slug": "saalekreis",
    "bl": "15"
  },
  "15089": {
    "slug": "salzlandkreis",
    "bl": "15"
  },
  "15090": {
    "slug": "stendal",
    "bl": "15"
  },
  "15091": {
    "slug": "wittenberg",
    "bl": "15"
  },
  "16051": {
    "slug": "erfurt-stadt",
    "bl": "16"
  },
  "16052": {
    "slug": "gera-stadt",
    "bl": "16"
  },
  "16053": {
    "slug": "jena-stadt",
    "bl": "16"
  },
  "16054": {
    "slug": "suhl-stadt",
    "bl": "16"
  },
  "16055": {
    "slug": "weimar-stadt",
    "bl": "16"
  },
  "16061": {
    "slug": "eichsfeld",
    "bl": "16"
  },
  "16062": {
    "slug": "nordhausen",
    "bl": "16"
  },
  "16063": {
    "slug": "wartburgkreis",
    "bl": "16"
  },
  "16064": {
    "slug": "unstrut-hainich-kreis",
    "bl": "16"
  },
  "16065": {
    "slug": "kyffhaeuserkreis",
    "bl": "16"
  },
  "16066": {
    "slug": "schmalkalden-meiningen",
    "bl": "16"
  },
  "16067": {
    "slug": "gotha",
    "bl": "16"
  },
  "16068": {
    "slug": "soemmerda",
    "bl": "16"
  },
  "16069": {
    "slug": "hildburghausen",
    "bl": "16"
  },
  "16070": {
    "slug": "ilm-kreis",
    "bl": "16"
  },
  "16071": {
    "slug": "weimarer-land",
    "bl": "16"
  },
  "16072": {
    "slug": "sonneberg",
    "bl": "16"
  },
  "16073": {
    "slug": "saalfeld-rudolstadt",
    "bl": "16"
  },
  "16074": {
    "slug": "saale-holzland-kreis",
    "bl": "16"
  },
  "16075": {
    "slug": "saale-orla-kreis",
    "bl": "16"
  },
  "16076": {
    "slug": "greiz",
    "bl": "16"
  },
  "16077": {
    "slug": "altenburger-land",
    "bl": "16"
  },
  "01054": {
    "slug": "nordfriesland",
    "bl": "01"
  },
  "07143": {
    "slug": "westerwaldkreis",
    "bl": "07"
  },
  "07211": {
    "slug": "trier-stadt",
    "bl": "07"
  },
  "08325": {
    "slug": "rottweil",
    "bl": "08"
  },
  "08335": {
    "slug": "konstanz",
    "bl": "08"
  },
  "09462": {
    "slug": "bayreuth-stadt",
    "bl": "09"
  },
  "09479": {
    "slug": "wunsiedel-i-fichtelgebirge",
    "bl": "09"
  },
  "09678": {
    "slug": "schweinfurt",
    "bl": "09"
  },
  "01003": {
    "slug": "luebeck-stadt",
    "bl": "01"
  },
  "03251": {
    "slug": "diepholz",
    "bl": "03"
  },
  "03254": {
    "slug": "hildesheim",
    "bl": "03"
  },
  "06635": {
    "slug": "waldeck-frankenberg",
    "bl": "06"
  },
  "08125": {
    "slug": "heilbronn",
    "bl": "08"
  },
  "08435": {
    "slug": "bodenseekreis",
    "bl": "08"
  },
  "09375": {
    "slug": "regensburg",
    "bl": "09"
  },
  "09572": {
    "slug": "erlangen-hoechstadt",
    "bl": "09"
  },
  "09762": {
    "slug": "kaufbeuren-stadt",
    "bl": "09"
  },
  "01056": {
    "slug": "pinneberg",
    "bl": "01"
  },
  "06413": {
    "slug": "offenbach-am-main-stadt",
    "bl": "06"
  },
  "06440": {
    "slug": "wetteraukreis",
    "bl": "06"
  },
  "06633": {
    "slug": "kassel",
    "bl": "06"
  },
  "07140": {
    "slug": "rhein-hunsrueck-kreis",
    "bl": "07"
  },
  "08111": {
    "slug": "stuttgart-stadt",
    "bl": "08"
  },
  "08121": {
    "slug": "heilbronn-stadt",
    "bl": "08"
  },
  "08215": {
    "slug": "karlsruhe",
    "bl": "08"
  },
  "08235": {
    "slug": "calw",
    "bl": "08"
  },
  "08326": {
    "slug": "schwarzwald-baar-kreis",
    "bl": "08"
  },
  "09162": {
    "slug": "muenchen-stadt",
    "bl": "09"
  },
  "09185": {
    "slug": "neuburg-schrobenhausen",
    "bl": "09"
  },
  "09262": {
    "slug": "passau-stadt",
    "bl": "09"
  },
  "09271": {
    "slug": "deggendorf",
    "bl": "09"
  },
  "09463": {
    "slug": "coburg-stadt",
    "bl": "09"
  },
  "09663": {
    "slug": "wuerzburg-stadt",
    "bl": "09"
  },
  "01004": {
    "slug": "neumuenster-stadt",
    "bl": "01"
  },
  "03256": {
    "slug": "nienburg-weser",
    "bl": "03"
  },
  "03354": {
    "slug": "luechow-dannenberg",
    "bl": "03"
  },
  "05119": {
    "slug": "oberhausen-stadt",
    "bl": "05"
  },
  "08116": {
    "slug": "esslingen",
    "bl": "08"
  },
  "09276": {
    "slug": "regen",
    "bl": "09"
  },
  "09278": {
    "slug": "straubing-bogen",
    "bl": "09"
  },
  "09764": {
    "slug": "memmingen-stadt",
    "bl": "09"
  },
  "06412": {
    "slug": "frankfurt-am-main-stadt",
    "bl": "06"
  },
  "07316": {
    "slug": "neustadt-an-der-weinstrasse-stadt",
    "bl": "07"
  },
  "07317": {
    "slug": "pirmasens-stadt",
    "bl": "07"
  },
  "08226": {
    "slug": "rhein-neckar-kreis",
    "bl": "08"
  },
  "09571": {
    "slug": "ansbach",
    "bl": "09"
  },
  "03358": {
    "slug": "heidekreis",
    "bl": "03"
  },
  "03454": {
    "slug": "emsland",
    "bl": "03"
  },
  "05116": {
    "slug": "moenchengladbach-stadt",
    "bl": "05"
  },
  "05154": {
    "slug": "kleve",
    "bl": "05"
  },
  "05754": {
    "slug": "guetersloh",
    "bl": "05"
  },
  "06634": {
    "slug": "schwalm-eder-kreis",
    "bl": "06"
  },
  "08118": {
    "slug": "ludwigsburg",
    "bl": "08"
  },
  "08216": {
    "slug": "rastatt",
    "bl": "08"
  },
  "09372": {
    "slug": "cham",
    "bl": "09"
  },
  "09761": {
    "slug": "augsburg-stadt",
    "bl": "09"
  },
  "01058": {
    "slug": "rendsburg-eckernfoerde",
    "bl": "01"
  },
  "01059": {
    "slug": "schleswig-flensburg",
    "bl": "01"
  },
  "04012": {
    "slug": "bremerhaven-stadt",
    "bl": "04"
  },
  "05117": {
    "slug": "muelheim-an-der-ruhr-stadt",
    "bl": "05"
  },
  "05382": {
    "slug": "rhein-sieg-kreis",
    "bl": "05"
  },
  "06414": {
    "slug": "wiesbaden-stadt",
    "bl": "06"
  },
  "07231": {
    "slug": "bernkastel-wittlich",
    "bl": "07"
  },
  "07332": {
    "slug": "bad-duerkheim",
    "bl": "07"
  },
  "09176": {
    "slug": "eichstaett",
    "bl": "09"
  },
  "09184": {
    "slug": "muenchen",
    "bl": "09"
  },
  "09472": {
    "slug": "bayreuth",
    "bl": "09"
  },
  "09576": {
    "slug": "roth",
    "bl": "09"
  },
  "09671": {
    "slug": "aschaffenburg",
    "bl": "09"
  },
  "09773": {
    "slug": "dillingen-a-d-donau",
    "bl": "09"
  },
  "04011": {
    "slug": "bremen-stadt",
    "bl": "04"
  },
  "05911": {
    "slug": "bochum-stadt",
    "bl": "05"
  },
  "06432": {
    "slug": "darmstadt-dieburg",
    "bl": "06"
  },
  "07135": {
    "slug": "cochem-zell",
    "bl": "07"
  },
  "07313": {
    "slug": "landau-in-der-pfalz-stadt",
    "bl": "07"
  },
  "08315": {
    "slug": "breisgau-hochschwarzwald",
    "bl": "08"
  },
  "08421": {
    "slug": "ulm-stadt",
    "bl": "08"
  },
  "09178": {
    "slug": "freising",
    "bl": "09"
  },
  "05970": {
    "slug": "siegen-wittgenstein",
    "bl": "05"
  },
  "06535": {
    "slug": "vogelsbergkreis",
    "bl": "06"
  },
  "07111": {
    "slug": "koblenz-stadt",
    "bl": "07"
  },
  "09273": {
    "slug": "kelheim",
    "bl": "09"
  },
  "09377": {
    "slug": "tirschenreuth",
    "bl": "09"
  },
  "09477": {
    "slug": "kulmbach",
    "bl": "09"
  },
  "09661": {
    "slug": "aschaffenburg-stadt",
    "bl": "09"
  },
  "09777": {
    "slug": "ostallgaeu",
    "bl": "09"
  },
  "03402": {
    "slug": "emden-stadt",
    "bl": "03"
  },
  "05513": {
    "slug": "gelsenkirchen-stadt",
    "bl": "05"
  },
  "07138": {
    "slug": "neuwied",
    "bl": "07"
  },
  "07331": {
    "slug": "alzey-worms",
    "bl": "07"
  },
  "08221": {
    "slug": "heidelberg-stadt",
    "bl": "08"
  },
  "09272": {
    "slug": "freyung-grafenau",
    "bl": "09"
  },
  "09275": {
    "slug": "passau",
    "bl": "09"
  },
  "09371": {
    "slug": "amberg-sulzbach",
    "bl": "09"
  },
  "03101": {
    "slug": "braunschweig-stadt",
    "bl": "03"
  },
  "03351": {
    "slug": "celle",
    "bl": "03"
  },
  "03451": {
    "slug": "ammerland",
    "bl": "03"
  },
  "03455": {
    "slug": "friesland",
    "bl": "03"
  },
  "03460": {
    "slug": "vechta",
    "bl": "03"
  },
  "05711": {
    "slug": "bielefeld-stadt",
    "bl": "05"
  },
  "06534": {
    "slug": "marburg-biedenkopf",
    "bl": "06"
  },
  "06611": {
    "slug": "kassel-stadt",
    "bl": "06"
  },
  "08119": {
    "slug": "rems-murr-kreis",
    "bl": "08"
  },
  "09261": {
    "slug": "landshut-stadt",
    "bl": "09"
  },
  "09564": {
    "slug": "nuernberg-stadt",
    "bl": "09"
  },
  "09679": {
    "slug": "wuerzburg",
    "bl": "09"
  },
  "09780": {
    "slug": "oberallgaeu",
    "bl": "09"
  },
  "03252": {
    "slug": "hameln-pyrmont",
    "bl": "03"
  },
  "05112": {
    "slug": "duisburg-stadt",
    "bl": "05"
  },
  "05770": {
    "slug": "minden-luebbecke",
    "bl": "05"
  },
  "07315": {
    "slug": "mainz-stadt",
    "bl": "07"
  },
  "08136": {
    "slug": "ostalbkreis",
    "bl": "08"
  },
  "08237": {
    "slug": "freudenstadt",
    "bl": "08"
  },
  "09187": {
    "slug": "rosenheim",
    "bl": "09"
  },
  "09362": {
    "slug": "regensburg-stadt",
    "bl": "09"
  },
  "09662": {
    "slug": "schweinfurt-stadt",
    "bl": "09"
  },
  "09774": {
    "slug": "guenzburg",
    "bl": "09"
  },
  "01002": {
    "slug": "kiel-stadt",
    "bl": "01"
  },
  "05111": {
    "slug": "duesseldorf-stadt",
    "bl": "05"
  },
  "05334": {
    "slug": "staedteregion-aachen",
    "bl": "05"
  },
  "05762": {
    "slug": "hoexter",
    "bl": "05"
  },
  "05916": {
    "slug": "herne-stadt",
    "bl": "05"
  },
  "07333": {
    "slug": "donnersbergkreis",
    "bl": "07"
  },
  "08311": {
    "slug": "freiburg-im-breisgau-stadt",
    "bl": "08"
  },
  "08336": {
    "slug": "loerrach",
    "bl": "08"
  },
  "09373": {
    "slug": "neumarkt-i-d-opf",
    "bl": "09"
  },
  "09561": {
    "slug": "ansbach-stadt",
    "bl": "09"
  },
  "01057": {
    "slug": "ploen",
    "bl": "01"
  },
  "03103": {
    "slug": "wolfsburg-stadt",
    "bl": "03"
  },
  "03154": {
    "slug": "helmstedt",
    "bl": "03"
  },
  "03158": {
    "slug": "wolfenbuettel",
    "bl": "03"
  },
  "03405": {
    "slug": "wilhelmshaven-stadt",
    "bl": "03"
  },
  "03459": {
    "slug": "osnabrueck",
    "bl": "03"
  },
  "08426": {
    "slug": "biberach",
    "bl": "08"
  },
  "09173": {
    "slug": "bad-toelz-wolfratshausen",
    "bl": "09"
  },
  "09190": {
    "slug": "weilheim-schongau",
    "bl": "09"
  },
  "09376": {
    "slug": "schwandorf",
    "bl": "09"
  },
  "09475": {
    "slug": "hof",
    "bl": "09"
  },
  "09674": {
    "slug": "hassberge",
    "bl": "09"
  },
  "09676": {
    "slug": "miltenberg",
    "bl": "09"
  },
  "09779": {
    "slug": "donau-ries",
    "bl": "09"
  },
  "01053": {
    "slug": "herzogtum-lauenburg",
    "bl": "01"
  },
  "03159": {
    "slug": "goettingen",
    "bl": "03"
  },
  "03461": {
    "slug": "wesermarsch",
    "bl": "03"
  },
  "05362": {
    "slug": "rhein-erft-kreis",
    "bl": "05"
  },
  "05774": {
    "slug": "paderborn",
    "bl": "05"
  },
  "06431": {
    "slug": "bergstrasse",
    "bl": "06"
  },
  "07320": {
    "slug": "zweibruecken-stadt",
    "bl": "07"
  },
  "08236": {
    "slug": "enzkreis",
    "bl": "08"
  },
  "09161": {
    "slug": "ingolstadt-stadt",
    "bl": "09"
  },
  "09172": {
    "slug": "berchtesgadener-land",
    "bl": "09"
  },
  "09175": {
    "slug": "ebersberg",
    "bl": "09"
  },
  "09771": {
    "slug": "aichach-friedberg",
    "bl": "09"
  },
  "09772": {
    "slug": "augsburg",
    "bl": "09"
  },
  "03151": {
    "slug": "gifhorn",
    "bl": "03"
  },
  "03452": {
    "slug": "aurich",
    "bl": "03"
  },
  "05158": {
    "slug": "mettmann",
    "bl": "05"
  },
  "05914": {
    "slug": "hagen-stadt",
    "bl": "05"
  },
  "05966": {
    "slug": "olpe",
    "bl": "05"
  },
  "05978": {
    "slug": "unna",
    "bl": "05"
  },
  "06411": {
    "slug": "darmstadt-stadt",
    "bl": "06"
  },
  "06438": {
    "slug": "offenbach",
    "bl": "06"
  },
  "07133": {
    "slug": "bad-kreuznach",
    "bl": "07"
  },
  "08436": {
    "slug": "ravensburg",
    "bl": "08"
  },
  "08437": {
    "slug": "sigmaringen",
    "bl": "08"
  },
  "09171": {
    "slug": "altoetting",
    "bl": "09"
  },
  "09577": {
    "slug": "weissenburg-gunzenhausen",
    "bl": "09"
  },
  "09776": {
    "slug": "lindau-bodensee",
    "bl": "09"
  },
  "02000": {
    "slug": "hamburg-stadt",
    "bl": "02"
  },
  "03255": {
    "slug": "holzminden",
    "bl": "03"
  },
  "03352": {
    "slug": "cuxhaven",
    "bl": "03"
  },
  "03404": {
    "slug": "osnabrueck-stadt",
    "bl": "03"
  },
  "05120": {
    "slug": "remscheid-stadt",
    "bl": "05"
  },
  "05162": {
    "slug": "rhein-kreis-neuss",
    "bl": "05"
  },
  "05374": {
    "slug": "oberbergischer-kreis",
    "bl": "05"
  },
  "06532": {
    "slug": "lahn-dill-kreis",
    "bl": "06"
  },
  "07131": {
    "slug": "ahrweiler",
    "bl": "07"
  },
  "07340": {
    "slug": "suedwestpfalz",
    "bl": "07"
  },
  "08117": {
    "slug": "goeppingen",
    "bl": "08"
  },
  "08225": {
    "slug": "neckar-odenwald-kreis",
    "bl": "08"
  },
  "09473": {
    "slug": "coburg",
    "bl": "09"
  },
  "01051": {
    "slug": "dithmarschen",
    "bl": "01"
  },
  "03102": {
    "slug": "salzgitter-stadt",
    "bl": "03"
  },
  "03353": {
    "slug": "harburg",
    "bl": "03"
  },
  "03457": {
    "slug": "leer",
    "bl": "03"
  },
  "05113": {
    "slug": "essen-stadt",
    "bl": "05"
  },
  "05378": {
    "slug": "rheinisch-bergischer-kreis",
    "bl": "05"
  },
  "05570": {
    "slug": "warendorf",
    "bl": "05"
  },
  "05958": {
    "slug": "hochsauerlandkreis",
    "bl": "05"
  },
  "07134": {
    "slug": "birkenfeld",
    "bl": "07"
  },
  "08416": {
    "slug": "tuebingen",
    "bl": "08"
  },
  "08417": {
    "slug": "zollernalbkreis",
    "bl": "08"
  },
  "09474": {
    "slug": "forchheim",
    "bl": "09"
  },
  "05315": {
    "slug": "koeln-stadt",
    "bl": "05"
  },
  "05566": {
    "slug": "steinfurt",
    "bl": "05"
  },
  "06436": {
    "slug": "main-taunus-kreis",
    "bl": "06"
  },
  "06531": {
    "slug": "giessen",
    "bl": "06"
  },
  "07235": {
    "slug": "trier-saarburg",
    "bl": "07"
  },
  "09186": {
    "slug": "pfaffenhofen-a-d-ilm",
    "bl": "09"
  },
  "09189": {
    "slug": "traunstein",
    "bl": "09"
  },
  "03359": {
    "slug": "stade",
    "bl": "03"
  },
  "03456": {
    "slug": "grafschaft-bentheim",
    "bl": "03"
  },
  "03458": {
    "slug": "oldenburg",
    "bl": "03"
  },
  "03462": {
    "slug": "wittmund",
    "bl": "03"
  },
  "05915": {
    "slug": "hamm-stadt",
    "bl": "05"
  },
  "05954": {
    "slug": "ennepe-ruhr-kreis",
    "bl": "05"
  },
  "06439": {
    "slug": "rheingau-taunus-kreis",
    "bl": "06"
  },
  "07318": {
    "slug": "speyer-stadt",
    "bl": "07"
  },
  "08127": {
    "slug": "schwaebisch-hall",
    "bl": "08"
  },
  "08212": {
    "slug": "karlsruhe-stadt",
    "bl": "08"
  },
  "08317": {
    "slug": "ortenaukreis",
    "bl": "08"
  },
  "08327": {
    "slug": "tuttlingen",
    "bl": "08"
  },
  "08337": {
    "slug": "waldshut",
    "bl": "08"
  },
  "09277": {
    "slug": "rottal-inn",
    "bl": "09"
  },
  "09464": {
    "slug": "hof-stadt",
    "bl": "09"
  },
  "09677": {
    "slug": "main-spessart",
    "bl": "09"
  },
  "09163": {
    "slug": "rosenheim-stadt",
    "bl": "09"
  },
  "09672": {
    "slug": "bad-kissingen",
    "bl": "09"
  },
  "03155": {
    "slug": "northeim",
    "bl": "03"
  },
  "03356": {
    "slug": "osterholz",
    "bl": "03"
  },
  "05758": {
    "slug": "herford",
    "bl": "05"
  },
  "05974": {
    "slug": "soest",
    "bl": "05"
  },
  "06435": {
    "slug": "main-kinzig-kreis",
    "bl": "06"
  },
  "07233": {
    "slug": "vulkaneifel",
    "bl": "07"
  },
  "07335": {
    "slug": "kaiserslautern",
    "bl": "07"
  },
  "01001": {
    "slug": "flensburg-stadt",
    "bl": "01"
  },
  "03401": {
    "slug": "delmenhorst-stadt",
    "bl": "03"
  },
  "03403": {
    "slug": "oldenburg-oldb-stadt",
    "bl": "03"
  },
  "05370": {
    "slug": "heinsberg",
    "bl": "05"
  },
  "05913": {
    "slug": "dortmund-stadt",
    "bl": "05"
  },
  "07319": {
    "slug": "worms-stadt",
    "bl": "07"
  },
  "08126": {
    "slug": "hohenlohekreis",
    "bl": "08"
  },
  "09188": {
    "slug": "starnberg",
    "bl": "09"
  },
  "09478": {
    "slug": "lichtenfels",
    "bl": "09"
  },
  "09565": {
    "slug": "schwabach-stadt",
    "bl": "09"
  },
  "09675": {
    "slug": "kitzingen",
    "bl": "09"
  },
  "01055": {
    "slug": "ostholstein",
    "bl": "01"
  },
  "03157": {
    "slug": "peine",
    "bl": "03"
  },
  "03257": {
    "slug": "schaumburg",
    "bl": "03"
  },
  "03361": {
    "slug": "verden",
    "bl": "03"
  },
  "05124": {
    "slug": "wuppertal-stadt",
    "bl": "05"
  },
  "05316": {
    "slug": "leverkusen-stadt",
    "bl": "05"
  },
  "05358": {
    "slug": "dueren",
    "bl": "05"
  },
  "05366": {
    "slug": "euskirchen",
    "bl": "05"
  },
  "05512": {
    "slug": "bottrop-stadt",
    "bl": "05"
  },
  "05766": {
    "slug": "lippe",
    "bl": "05"
  },
  "06437": {
    "slug": "odenwaldkreis",
    "bl": "06"
  },
  "06632": {
    "slug": "hersfeld-rotenburg",
    "bl": "06"
  },
  "07137": {
    "slug": "mayen-koblenz",
    "bl": "07"
  },
  "07141": {
    "slug": "rhein-lahn-kreis",
    "bl": "07"
  },
  "07336": {
    "slug": "kusel",
    "bl": "07"
  },
  "07339": {
    "slug": "mainz-bingen",
    "bl": "07"
  },
  "08231": {
    "slug": "pforzheim-stadt",
    "bl": "08"
  },
  "08316": {
    "slug": "emmendingen",
    "bl": "08"
  },
  "09181": {
    "slug": "landsberg-am-lech",
    "bl": "09"
  },
  "09274": {
    "slug": "landshut",
    "bl": "09"
  },
  "09279": {
    "slug": "dingolfing-landau",
    "bl": "09"
  },
  "09562": {
    "slug": "erlangen-stadt",
    "bl": "09"
  },
  "05562": {
    "slug": "recklinghausen",
    "bl": "05"
  },
  "06434": {
    "slug": "hochtaunuskreis",
    "bl": "06"
  },
  "06631": {
    "slug": "fulda",
    "bl": "06"
  },
  "07132": {
    "slug": "altenkirchen-westerwald",
    "bl": "07"
  },
  "07334": {
    "slug": "germersheim",
    "bl": "07"
  },
  "08115": {
    "slug": "boeblingen",
    "bl": "08"
  },
  "09563": {
    "slug": "fuerth-stadt",
    "bl": "09"
  },
  "08222": {
    "slug": "mannheim-stadt",
    "bl": "08"
  },
  "09177": {
    "slug": "erding",
    "bl": "09"
  },
  "01062": {
    "slug": "stormarn",
    "bl": "01"
  },
  "03357": {
    "slug": "rotenburg-wuemme",
    "bl": "03"
  },
  "03360": {
    "slug": "uelzen",
    "bl": "03"
  },
  "05166": {
    "slug": "viersen",
    "bl": "05"
  },
  "05170": {
    "slug": "wesel",
    "bl": "05"
  },
  "05962": {
    "slug": "maerkischer-kreis",
    "bl": "05"
  },
  "07338": {
    "slug": "rhein-pfalz-kreis",
    "bl": "07"
  },
  "08135": {
    "slug": "heidenheim",
    "bl": "08"
  },
  "08211": {
    "slug": "baden-baden-stadt",
    "bl": "08"
  },
  "09374": {
    "slug": "neustadt-a-d-waldnaab",
    "bl": "09"
  },
  "09461": {
    "slug": "bamberg-stadt",
    "bl": "09"
  },
  "09476": {
    "slug": "kronach",
    "bl": "09"
  },
  "09573": {
    "slug": "fuerth",
    "bl": "09"
  },
  "01061": {
    "slug": "steinburg",
    "bl": "01"
  },
  "03241": {
    "slug": "region-hannover",
    "bl": "03"
  },
  "03355": {
    "slug": "lueneburg",
    "bl": "03"
  },
  "05114": {
    "slug": "krefeld-stadt",
    "bl": "05"
  },
  "05314": {
    "slug": "bonn-stadt",
    "bl": "05"
  },
  "05558": {
    "slug": "coesfeld",
    "bl": "05"
  },
  "06636": {
    "slug": "werra-meissner-kreis",
    "bl": "06"
  },
  "07312": {
    "slug": "kaiserslautern-stadt",
    "bl": "07"
  },
  "07314": {
    "slug": "ludwigshafen-am-rhein-stadt",
    "bl": "07"
  },
  "07337": {
    "slug": "suedliche-weinstrasse",
    "bl": "07"
  },
  "08128": {
    "slug": "main-tauber-kreis",
    "bl": "08"
  },
  "09174": {
    "slug": "dachau",
    "bl": "09"
  },
  "09471": {
    "slug": "bamberg",
    "bl": "09"
  },
  "09673": {
    "slug": "rhoen-grabfeld",
    "bl": "09"
  },
  "09775": {
    "slug": "neu-ulm",
    "bl": "09"
  },
  "09778": {
    "slug": "unterallgaeu",
    "bl": "09"
  },
  "01060": {
    "slug": "segeberg",
    "bl": "01"
  },
  "05122": {
    "slug": "solingen-stadt",
    "bl": "05"
  },
  "05515": {
    "slug": "muenster-stadt",
    "bl": "05"
  },
  "08425": {
    "slug": "alb-donau-kreis",
    "bl": "08"
  },
  "09179": {
    "slug": "fuerstenfeldbruck",
    "bl": "09"
  },
  "09183": {
    "slug": "muehldorf-a-inn",
    "bl": "09"
  },
  "09263": {
    "slug": "straubing-stadt",
    "bl": "09"
  },
  "09574": {
    "slug": "nuernberger-land",
    "bl": "09"
  },
  "09575": {
    "slug": "neustadt-a-d-aisch-bad-windsheim",
    "bl": "09"
  },
  "03153": {
    "slug": "goslar",
    "bl": "03"
  },
  "03453": {
    "slug": "cloppenburg",
    "bl": "03"
  },
  "05554": {
    "slug": "borken",
    "bl": "05"
  },
  "06433": {
    "slug": "gross-gerau",
    "bl": "06"
  },
  "06533": {
    "slug": "limburg-weilburg",
    "bl": "06"
  },
  "07232": {
    "slug": "eifelkreis-bitburg-pruem",
    "bl": "07"
  },
  "07311": {
    "slug": "frankenthal-pfalz-stadt",
    "bl": "07"
  },
  "08415": {
    "slug": "reutlingen",
    "bl": "08"
  },
  "09180": {
    "slug": "garmisch-partenkirchen",
    "bl": "09"
  },
  "09182": {
    "slug": "miesbach",
    "bl": "09"
  },
  "09361": {
    "slug": "amberg-stadt",
    "bl": "09"
  },
  "09363": {
    "slug": "weiden-i-d-opf-stadt",
    "bl": "09"
  },
  "09763": {
    "slug": "kempten-allgaeu-stadt",
    "bl": "09"
  }
};

export const KREIS_SLUG_TO_AGS: Record<string, string> = {
  "01/nordfriesland": "01054",
  "07/westerwaldkreis": "07143",
  "07/trier-stadt": "07211",
  "08/rottweil": "08325",
  "08/konstanz": "08335",
  "09/bayreuth-stadt": "09462",
  "09/wunsiedel-i-fichtelgebirge": "09479",
  "09/schweinfurt": "09678",
  "10/neunkirchen": "10043",
  "16/gotha": "16067",
  "01/luebeck-stadt": "01003",
  "03/diepholz": "03251",
  "03/hildesheim": "03254",
  "06/waldeck-frankenberg": "06635",
  "08/heilbronn": "08125",
  "08/bodenseekreis": "08435",
  "09/regensburg": "09375",
  "09/erlangen-hoechstadt": "09572",
  "09/kaufbeuren-stadt": "09762",
  "12/havelland": "12063",
  "14/mittelsachsen": "14522",
  "14/vogtlandkreis": "14523",
  "14/dresden-stadt": "14612",
  "01/pinneberg": "01056",
  "06/offenbach-am-main-stadt": "06413",
  "06/wetteraukreis": "06440",
  "06/kassel": "06633",
  "07/rhein-hunsrueck-kreis": "07140",
  "08/stuttgart-stadt": "08111",
  "08/heilbronn-stadt": "08121",
  "08/karlsruhe": "08215",
  "08/calw": "08235",
  "08/schwarzwald-baar-kreis": "08326",
  "09/muenchen-stadt": "09162",
  "09/neuburg-schrobenhausen": "09185",
  "09/passau-stadt": "09262",
  "09/deggendorf": "09271",
  "09/coburg-stadt": "09463",
  "09/wuerzburg-stadt": "09663",
  "10/st-wendel": "10046",
  "16/schmalkalden-meiningen": "16066",
  "01/neumuenster-stadt": "01004",
  "03/nienburg-weser": "03256",
  "03/luechow-dannenberg": "03354",
  "05/oberhausen-stadt": "05119",
  "08/esslingen": "08116",
  "09/regen": "09276",
  "09/straubing-bogen": "09278",
  "09/memmingen-stadt": "09764",
  "14/meissen": "14627",
  "15/harz": "15085",
  "16/weimar-stadt": "16055",
  "16/greiz": "16076",
  "06/frankfurt-am-main-stadt": "06412",
  "07/neustadt-an-der-weinstrasse-stadt": "07316",
  "07/pirmasens-stadt": "07317",
  "08/rhein-neckar-kreis": "08226",
  "09/ansbach": "09571",
  "12/spree-neisse": "12071",
  "16/ilm-kreis": "16070",
  "16/saale-orla-kreis": "16075",
  "03/heidekreis": "03358",
  "03/emsland": "03454",
  "05/moenchengladbach-stadt": "05116",
  "05/kleve": "05154",
  "05/guetersloh": "05754",
  "06/schwalm-eder-kreis": "06634",
  "08/ludwigsburg": "08118",
  "08/rastatt": "08216",
  "09/cham": "09372",
  "09/augsburg-stadt": "09761",
  "13/vorpommern-greifswald": "13075",
  "14/chemnitz-stadt": "14511",
  "01/rendsburg-eckernfoerde": "01058",
  "01/schleswig-flensburg": "01059",
  "04/bremerhaven-stadt": "04012",
  "05/muelheim-an-der-ruhr-stadt": "05117",
  "05/rhein-sieg-kreis": "05382",
  "06/wiesbaden-stadt": "06414",
  "07/bernkastel-wittlich": "07231",
  "07/bad-duerkheim": "07332",
  "09/eichstaett": "09176",
  "09/muenchen": "09184",
  "09/bayreuth": "09472",
  "09/roth": "09576",
  "09/aschaffenburg": "09671",
  "09/dillingen-a-d-donau": "09773",
  "12/elbe-elster": "12062",
  "12/prignitz": "12070",
  "13/schwerin-stadt": "13004",
  "14/leipzig-stadt": "14713",
  "16/wartburgkreis": "16063",
  "16/kyffhaeuserkreis": "16065",
  "04/bremen-stadt": "04011",
  "05/bochum-stadt": "05911",
  "06/darmstadt-dieburg": "06432",
  "07/cochem-zell": "07135",
  "07/landau-in-der-pfalz-stadt": "07313",
  "08/breisgau-hochschwarzwald": "08315",
  "08/ulm-stadt": "08421",
  "09/freising": "09178",
  "13/rostock-stadt": "13003",
  "15/halle-saale-stadt": "15002",
  "15/boerde": "15083",
  "16/erfurt-stadt": "16051",
  "05/siegen-wittgenstein": "05970",
  "06/vogelsbergkreis": "06535",
  "07/koblenz-stadt": "07111",
  "09/kelheim": "09273",
  "09/tirschenreuth": "09377",
  "09/kulmbach": "09477",
  "09/aschaffenburg-stadt": "09661",
  "09/ostallgaeu": "09777",
  "12/maerkisch-oderland": "12064",
  "15/saalekreis": "15088",
  "16/nordhausen": "16062",
  "16/altenburger-land": "16077",
  "03/emden-stadt": "03402",
  "05/gelsenkirchen-stadt": "05513",
  "07/neuwied": "07138",
  "07/alzey-worms": "07331",
  "08/heidelberg-stadt": "08221",
  "09/freyung-grafenau": "09272",
  "09/passau": "09275",
  "09/amberg-sulzbach": "09371",
  "11/berlin-stadt": "11000",
  "12/brandenburg-an-der-havel-stadt": "12051",
  "12/potsdam-mittelmark": "12069",
  "12/uckermark": "12073",
  "03/braunschweig-stadt": "03101",
  "03/celle": "03351",
  "03/ammerland": "03451",
  "03/friesland": "03455",
  "03/vechta": "03460",
  "05/bielefeld-stadt": "05711",
  "06/marburg-biedenkopf": "06534",
  "06/kassel-stadt": "06611",
  "08/rems-murr-kreis": "08119",
  "09/landshut-stadt": "09261",
  "09/nuernberg-stadt": "09564",
  "09/wuerzburg": "09679",
  "09/oberallgaeu": "09780",
  "14/erzgebirgskreis": "14521",
  "15/mansfeld-suedharz": "15087",
  "03/hameln-pyrmont": "03252",
  "05/duisburg-stadt": "05112",
  "05/minden-luebbecke": "05770",
  "07/mainz-stadt": "07315",
  "08/ostalbkreis": "08136",
  "08/freudenstadt": "08237",
  "09/rosenheim": "09187",
  "09/regensburg-stadt": "09362",
  "09/schweinfurt-stadt": "09662",
  "09/guenzburg": "09774",
  "10/saarpfalz-kreis": "10045",
  "12/frankfurt-oder-stadt": "12053",
  "16/hildburghausen": "16069",
  "16/weimarer-land": "16071",
  "01/kiel-stadt": "01002",
  "05/duesseldorf-stadt": "05111",
  "05/staedteregion-aachen": "05334",
  "05/hoexter": "05762",
  "05/herne-stadt": "05916",
  "07/donnersbergkreis": "07333",
  "08/freiburg-im-breisgau-stadt": "08311",
  "08/loerrach": "08336",
  "09/neumarkt-i-d-opf": "09373",
  "09/ansbach-stadt": "09561",
  "10/merzig-wadern": "10042",
  "16/saalfeld-rudolstadt": "16073",
  "01/ploen": "01057",
  "03/wolfsburg-stadt": "03103",
  "03/helmstedt": "03154",
  "03/wolfenbuettel": "03158",
  "03/wilhelmshaven-stadt": "03405",
  "03/osnabrueck": "03459",
  "08/biberach": "08426",
  "09/bad-toelz-wolfratshausen": "09173",
  "09/weilheim-schongau": "09190",
  "09/schwandorf": "09376",
  "09/hof": "09475",
  "09/hassberge": "09674",
  "09/miltenberg": "09676",
  "09/donau-ries": "09779",
  "15/altmarkkreis-salzwedel": "15081",
  "01/herzogtum-lauenburg": "01053",
  "03/goettingen": "03159",
  "03/wesermarsch": "03461",
  "05/rhein-erft-kreis": "05362",
  "05/paderborn": "05774",
  "06/bergstrasse": "06431",
  "07/zweibruecken-stadt": "07320",
  "08/enzkreis": "08236",
  "09/ingolstadt-stadt": "09161",
  "09/berchtesgadener-land": "09172",
  "09/ebersberg": "09175",
  "09/aichach-friedberg": "09771",
  "09/augsburg": "09772",
  "12/oberhavel": "12065",
  "16/soemmerda": "16068",
  "16/sonneberg": "16072",
  "03/gifhorn": "03151",
  "03/aurich": "03452",
  "05/mettmann": "05158",
  "05/hagen-stadt": "05914",
  "05/olpe": "05966",
  "05/unna": "05978",
  "06/darmstadt-stadt": "06411",
  "06/offenbach": "06438",
  "07/bad-kreuznach": "07133",
  "08/ravensburg": "08436",
  "08/sigmaringen": "08437",
  "09/altoetting": "09171",
  "09/weissenburg-gunzenhausen": "09577",
  "09/lindau-bodensee": "09776",
  "10/regionalverband-saarbruecken": "10041",
  "14/zwickau": "14524",
  "14/leipzig": "14729",
  "02/hamburg-stadt": "02000",
  "03/holzminden": "03255",
  "03/cuxhaven": "03352",
  "03/osnabrueck-stadt": "03404",
  "05/remscheid-stadt": "05120",
  "05/rhein-kreis-neuss": "05162",
  "05/oberbergischer-kreis": "05374",
  "06/lahn-dill-kreis": "06532",
  "07/ahrweiler": "07131",
  "07/suedwestpfalz": "07340",
  "08/goeppingen": "08117",
  "08/neckar-odenwald-kreis": "08225",
  "09/coburg": "09473",
  "10/saarlouis": "10044",
  "13/ludwigslust-parchim": "13076",
  "14/goerlitz": "14626",
  "01/dithmarschen": "01051",
  "03/salzgitter-stadt": "03102",
  "03/harburg": "03353",
  "03/leer": "03457",
  "05/essen-stadt": "05113",
  "05/rheinisch-bergischer-kreis": "05378",
  "05/warendorf": "05570",
  "05/hochsauerlandkreis": "05958",
  "07/birkenfeld": "07134",
  "08/tuebingen": "08416",
  "08/zollernalbkreis": "08417",
  "09/forchheim": "09474",
  "13/mecklenburgische-seenplatte": "13071",
  "13/nordwestmecklenburg": "13074",
  "15/jerichower-land": "15086",
  "16/jena-stadt": "16053",
  "05/koeln-stadt": "05315",
  "05/steinfurt": "05566",
  "06/main-taunus-kreis": "06436",
  "06/giessen": "06531",
  "07/trier-saarburg": "07235",
  "09/pfaffenhofen-a-d-ilm": "09186",
  "09/traunstein": "09189",
  "12/oberspreewald-lausitz": "12066",
  "15/stendal": "15090",
  "16/gera-stadt": "16052",
  "03/stade": "03359",
  "03/grafschaft-bentheim": "03456",
  "03/oldenburg": "03458",
  "03/wittmund": "03462",
  "05/hamm-stadt": "05915",
  "05/ennepe-ruhr-kreis": "05954",
  "06/rheingau-taunus-kreis": "06439",
  "07/speyer-stadt": "07318",
  "08/schwaebisch-hall": "08127",
  "08/karlsruhe-stadt": "08212",
  "08/ortenaukreis": "08317",
  "08/tuttlingen": "08327",
  "08/waldshut": "08337",
  "09/rottal-inn": "09277",
  "09/hof-stadt": "09464",
  "09/main-spessart": "09677",
  "13/rostock": "13072",
  "14/bautzen": "14625",
  "09/rosenheim-stadt": "09163",
  "09/bad-kissingen": "09672",
  "12/ostprignitz-ruppin": "12068",
  "12/teltow-flaeming": "12072",
  "15/magdeburg-stadt": "15003",
  "15/burgenlandkreis": "15084",
  "15/wittenberg": "15091",
  "16/saale-holzland-kreis": "16074",
  "03/northeim": "03155",
  "03/osterholz": "03356",
  "05/herford": "05758",
  "05/soest": "05974",
  "06/main-kinzig-kreis": "06435",
  "07/vulkaneifel": "07233",
  "07/kaiserslautern": "07335",
  "01/flensburg-stadt": "01001",
  "03/delmenhorst-stadt": "03401",
  "03/oldenburg-oldb-stadt": "03403",
  "05/heinsberg": "05370",
  "05/dortmund-stadt": "05913",
  "07/worms-stadt": "07319",
  "08/hohenlohekreis": "08126",
  "09/starnberg": "09188",
  "09/lichtenfels": "09478",
  "09/schwabach-stadt": "09565",
  "09/kitzingen": "09675",
  "15/dessau-rosslau-stadt": "15001",
  "01/ostholstein": "01055",
  "03/peine": "03157",
  "03/schaumburg": "03257",
  "03/verden": "03361",
  "05/wuppertal-stadt": "05124",
  "05/leverkusen-stadt": "05316",
  "05/dueren": "05358",
  "05/euskirchen": "05366",
  "05/bottrop-stadt": "05512",
  "05/lippe": "05766",
  "06/odenwaldkreis": "06437",
  "06/hersfeld-rotenburg": "06632",
  "07/mayen-koblenz": "07137",
  "07/rhein-lahn-kreis": "07141",
  "07/kusel": "07336",
  "07/mainz-bingen": "07339",
  "08/pforzheim-stadt": "08231",
  "08/emmendingen": "08316",
  "09/landsberg-am-lech": "09181",
  "09/landshut": "09274",
  "09/dingolfing-landau": "09279",
  "09/erlangen-stadt": "09562",
  "12/potsdam-stadt": "12054",
  "16/suhl-stadt": "16054",
  "05/recklinghausen": "05562",
  "06/hochtaunuskreis": "06434",
  "06/fulda": "06631",
  "07/altenkirchen-westerwald": "07132",
  "07/germersheim": "07334",
  "08/boeblingen": "08115",
  "09/fuerth-stadt": "09563",
  "13/vorpommern-ruegen": "13073",
  "08/mannheim-stadt": "08222",
  "09/erding": "09177",
  "01/stormarn": "01062",
  "03/rotenburg-wuemme": "03357",
  "03/uelzen": "03360",
  "05/viersen": "05166",
  "05/wesel": "05170",
  "05/maerkischer-kreis": "05962",
  "07/rhein-pfalz-kreis": "07338",
  "08/heidenheim": "08135",
  "08/baden-baden-stadt": "08211",
  "09/neustadt-a-d-waldnaab": "09374",
  "09/bamberg-stadt": "09461",
  "09/kronach": "09476",
  "09/fuerth": "09573",
  "12/oder-spree": "12067",
  "14/nordsachsen": "14730",
  "01/steinburg": "01061",
  "03/region-hannover": "03241",
  "03/lueneburg": "03355",
  "05/krefeld-stadt": "05114",
  "05/bonn-stadt": "05314",
  "05/coesfeld": "05558",
  "06/werra-meissner-kreis": "06636",
  "07/kaiserslautern-stadt": "07312",
  "07/ludwigshafen-am-rhein-stadt": "07314",
  "07/suedliche-weinstrasse": "07337",
  "08/main-tauber-kreis": "08128",
  "09/dachau": "09174",
  "09/bamberg": "09471",
  "09/rhoen-grabfeld": "09673",
  "09/neu-ulm": "09775",
  "09/unterallgaeu": "09778",
  "12/barnim": "12060",
  "15/salzlandkreis": "15089",
  "16/eichsfeld": "16061",
  "01/segeberg": "01060",
  "05/solingen-stadt": "05122",
  "05/muenster-stadt": "05515",
  "08/alb-donau-kreis": "08425",
  "09/fuerstenfeldbruck": "09179",
  "09/muehldorf-a-inn": "09183",
  "09/straubing-stadt": "09263",
  "09/nuernberger-land": "09574",
  "09/neustadt-a-d-aisch-bad-windsheim": "09575",
  "12/cottbus-stadt": "12052",
  "14/saechsische-schweiz-osterzgebirge": "14628",
  "15/anhalt-bitterfeld": "15082",
  "03/goslar": "03153",
  "03/cloppenburg": "03453",
  "05/borken": "05554",
  "06/gross-gerau": "06433",
  "06/limburg-weilburg": "06533",
  "07/eifelkreis-bitburg-pruem": "07232",
  "07/frankenthal-pfalz-stadt": "07311",
  "08/reutlingen": "08415",
  "09/garmisch-partenkirchen": "09180",
  "09/miesbach": "09182",
  "09/amberg-stadt": "09361",
  "09/weiden-i-d-opf-stadt": "09363",
  "09/kempten-allgaeu-stadt": "09763",
  "12/dahme-spreewald": "12061",
  "16/unstrut-hainich-kreis": "16064"
};

import { BL_META } from './bundeslaender';

export function kreisPath(ags: string): string {
  const entry = AGS_TO_KREIS_SLUG[ags];
  if (!entry) return `/kreis/${ags}`;
  const stateSlug = BL_META[entry.bl]?.slug ?? entry.bl;
  return `/kreis/${stateSlug}/${entry.slug}`;
}

export function kreisAgsFromSlugs(stateSlug: string, kreisSlug: string): string | undefined {
  const blEntry = Object.entries(BL_META).find(([, v]) => v.slug === stateSlug);
  if (!blEntry) return undefined;
  return KREIS_SLUG_TO_AGS[blEntry[0] + '/' + kreisSlug];
}
